### ISSUE TITLE
Install-Package Teamwork doesnt work

### ISSUE THREAD

**Issue by MattEllison** [Teamwork/dotnet#3]
**Describe the bug**
When I run `Install-Package Teamwork` I get unable to find package . When I searched the nuget store i found this `Install-Package Teamwork -Version 1.0.2-beta`. Is that correct?

**To Reproduce**
Run `Install-Package Teamwork` in package manager console

**Expected behavior**
Installs Nuget package

**Comment by DeeJayTC** [comment]
Hey, the library is still marked as pre-release in nuget. You need to use this:

Install-Package Teamwork -IncludePrerelease

Updated the read.me

Thanks for noting!
